apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-1
  region: es-east-1

managesnodeGroups:
  - name: expense
    instanceType: m5.large
    desiredCapacity: 3
    spot: true